name: Test

on:
  pull_request:
    branches:
      - master

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.14
      - run: |
          cat << EOF > .env
          ENV=staging
          AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION=${{ secrets.AWS_REGION }}
          EOF
      - run: node -e "let pkg=require('./package.json'); pkg.name='express-backend-staging'; require('fs').writeFileSync('package.json', JSON.stringify(pkg, null, 2));"
      - run: yarn install --frozen-lockfile
      - run: yarn test